Build & cache wxWidgets locally (#3)
* Build & cache wxWidgets locally

* Use latest wxWigets & build for oldest supported macOS

* Fix env var access syntax

* Use env vars consistently in uppercase

* Get wxWidgets from github

* Fix wxWidgets checkout paths

* Print/list working dirs, for debugging

* Define all checkout/build paths in one place

* Checkout wxWidgets by running git ourselves

actions/checkout requires the path to be inside GITHUB_WORKSPACE

* Clean up wxWidgets post-checkout setup

* Try building for macOS High Sierra

* Initialize git submodules required for wxWidgets

* Match target macOS version with Xcode project

* Try the stable version of wxWidgets

In case it'd build for macOS 10.9

* Build for macOS 10.10

Since both pwsafe & wxWidgets 3.0.5 will compile for macOS 10.9 but fail
to link with this error:

Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      wxPipeInputStream::CanRead() const in libwx_baseu-3.0.a(baselib_utilsunx.o)
      wxSelectSets::HasFD(int) const in libwx_baseu-3.0.a(baselib_selectdispatcher.o)
      wxSelectSets::SetFD(int, int) in libwx_baseu-3.0.a(baselib_selectdispatcher.o)
      wxSelectSets::Handle(int, wxFDIOHandler&) const in libwx_baseu-3.0.a(baselib_selectdispatcher.o)
      wxSelectDispatcher::UnregisterFD(int) in libwx_baseu-3.0.a(baselib_selectdispatcher.o)
      wxSelectDispatcher::ProcessSets(wxSelectSets const&) in libwx_baseu-3.0.a(baselib_selectdispatcher.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

* Try macOS 10.11 as target

since the buidl for 10.10 failed with the same linker error as 10.9

* Try building for macOS 10.12

* Try building for macOS 10.13

* Build for default macOS plaform for Xcode 10: 10.14

* Build with Xcode 11.7 for macOS 10.9

Co-authored-by: saurav <saurav@mbp>