VS2015 RC - Fix compiler error C2338: The C++ Standard forbids containers of const elements because allocator<const T> is ill-formed.
Signed-off-by: ronys <ronys@users.sourceforge.net>